FROM node:17-alpine

ENV HOME=/home/app
WORKDIR $HOME

COPY package.json .
COPY yarn.lock .
RUN yarn install
# Copy app files
COPY . .
# Expose port
EXPOSE 3000
# Start the app
CMD [ "yarn", "start" ]